3liz/lizmap-documentation

- en/source/publisher_guide/advanced_lizmap_config.rst
> More translation in source

- en/i18n/es/LC_MESSAGES/user_guide.po
> Spanish User_guide

- en/i18n/it/LC_MESSAGES/user_guide.po
> Translation of user guide - thanks Marta!

- source/admin_guide/installation/linux.rst
- source/admin_guide/installation/server_configuration.rst
- source/index.rst
- source/publisher_guide/advanced_lizmap_config.rst
Plus minor fixes to index.
Please note that I'm still uncertain about formatting. Sometimes commands are in *italic*, sometimes in **bold**, etc.
If you decide for explicit formatting rules, please add a file describing it, and I'll update the whole document.
> Optimization chapter added

- source/install/windows.rst
**Notes:**
- Tested with QGIS 2.8.9 64 bits (OsGeo4W64 Installer)
- Tested with PHP 5.6.23 and Apache 2.4.20.
- Windows 7, 10 (64 bits)
**TO DO LIST**
**Enhancement**
> Windows v0.1

- source/install/windows.rst
Changelog:
-> Add tip for windows firewall
-> change path from qgis to qgis-ltr
-> fix de configuration of postgresql drivers
> Minor fixes

- source/install/windows.rst
Changelog:
-> Add configuration when you write the php 5-x.x.x.cong file of Apache
> add php configuration for plugins in QGIS Server

- source/install/linux.rst
Update instalation instructions for linux and add some missing parts
> Install linux update

- source/install/linux.rst
haven't installed it yet, but in case I can try to update the howto to work with debian 9
> small note about php7 support

- source/publish/publish_with_ftp.rst
> Adding documentation for lftp mac osx users

- source/install/linux.rst
- source/publish/advanced_lizmap_config.rst
I got a drag and drop form and I saw it was displayed nicely in lizmap
> Lizmap knows Drag and drop form now

- source/publish/advanced_lizmap_config.rst
Is-it correct to make a PR against 3.2? (will it land in master later?)
I'm not sure it's correct about what I'm adding. Just guessing, but I think it's important to mention these variables.
> add tips about static URL

- source/install/windows.rst
Hi guys, finally the deserved upgrade. Sorry for my late, late contribution on this upgrade. I hope this upgrade helps other users. Please feel free to give opinions.
> Upgrade Windows Instalation for newers version

- README.md
- source/admin/lizmap-configuration.rst
- source/introduction.rst
- source/publish/configuration/legend.rst
- source/publish/customization/themes.rst
- source/publish/lizmap_plugin/edition.rst
- source/publish/lizmap_plugin/filtered_layers_login.rst
- source/publish/lizmap_plugin/locate_by_layer.rst
fix internal links, remove sphinx warnings fix #145
> fix internal links, remove sphinx warnings fix #145

- source/admin/users-groups.rst
Fix #148 
I will backport to 3.3
> add notes about setting up password as admins

- source/install/linux.rst
@laurentj What do you think?
Some users didn't follow QGIS Documentation, so they didn't configured NGinx on their server.
Let's just send people to the QGIS Documentation
> review the install of QGIS Server

- source/publish/customization/javascript.rst
@josemvm Does it work for you?
> add comment in javascript example

- source/install/linux.rst
Documentation for https://github.com/3liz/lizmap-web-client/pull/1515
> URL to check the state of QGIS Server

- source/install/upgrade.rst
In my opinion it is more clear for user and more homogeneous (e.g. using sudo in all line)
> Update of upgrade code

- source/install/linux.rst
I think it is useful for user which use apache (same configuration proposed by qgis documentation)
> Mantain also Apache configuration

- source/publish/customization/themes.rst
How to customize the default lizmap theme by modifying the modules templates.
* Ticket : #2532
*
> Custom template

- i18n/es/LC_MESSAGES/install.po
- i18n/fi/LC_MESSAGES/install.po
- i18n/fr/LC_MESSAGES/install.po
- i18n/it/LC_MESSAGES/install.po
- i18n/ja/LC_MESSAGES/install.po
- i18n/pot/install.pot
- i18n/pt/LC_MESSAGES/install.po
- i18n/ru/LC_MESSAGES/install.po
- source/install/pre_requirements.rst
Fix #189 
QGIS_PLUGIN_PATH to QGIS_PLUGINPATH
> typo - variable name QGIS_PLUGIN_PATH

- source/admin/cache.rst
- source/install/upgrade.rst
Update code exemple according to new commands that use `console.php` : 
https://github.com/3liz/lizmap-web-client/pull/3528
https://github.com/3liz/lizmap-web-client/pull/3480
https://github.com/3liz/lizmap-web-client/pull/3473
> update console example for + add wmts:clean

- source/publish/customization/javascript.rst
Add better example to get link to a media file from scratch
> Add better example to get link to a media file from scratch

- source/_static/css/custom.css
- source/_template/languageswitch.html
When using anchor link  browser don't scroll to proper position in content (scroll to sidebar link)
this PR remove absolute positionning
the content header is now beside the navbar and no more above  
So less space for version switcher : i use flexbox and widht breakpoints 
see large : 
medium
phone
> fix anchor scroll

- source/install/pre_requirements.rst
When installing Lizmap, there are a few things which are not explained in the documentation : 
* to know how to set environment variables (QGIS server for instance)
* restart and manage processes and read their respective logs stderr
* understand differences between QGIS server installation : apache, nginx, systemd, supervisor etc
> Add some notes about sysadmin skills when installing LWC

- source/install/pre_requirements.rst
- source/publish/configuration/popup.rst
Reverting manually beced1b8ef16a0e4daa78dfd11067232c833ba7b
> Add again AtlasPrint

- source/publish/configuration/media.rst
* Ticket : fix #263
* Erwan Vinot
> docs(media): clarify theme documentation and fix typo

- source/publish/lizmap_plugin/actions.rst
The action module using the new OpenLayers to display geometry, so the action style has to be adapted
https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html
Funded by Haute-Saone Numérique
> Fixing action style for new OpenLayers

- source/publish/configuration/spatial_search.rst
Linked to https://github.com/3liz/lizmap-web-client/pull/5619
> Add explanation to debug lizmap_search with DEBUG=TRUE

- source/install/index.rst
- source/install/pre_requirements.rst
- source/install/py-qgis-server.rst
Install Py-QGIS-Server documentation
> Install Py-QGIS-Server documentation
